"""Migration - 4

Revision ID: 091e6df65ba7
Revises: 30eec26aacc8
Create Date: 2021-02-25 21:20:58.024437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091e6df65ba7'
down_revision = '30eec26aacc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_no', sa.Integer(), nullable=True),
    sa.Column('option', sa.Integer(), nullable=True),
    sa.Column('paragraph_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('letter_id', 'paragraph_no', 'paragraph_text')
    )
    op.drop_table('copied')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copied',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('letter_id', sa.INTEGER(), nullable=True),
    sa.Column('paragraph_no', sa.INTEGER(), nullable=True),
    sa.Column('paragraph_text', sa.TEXT(), nullable=True),
    sa.Column('option', sa.INTEGER(), nullable=True)
    )
    op.drop_table('content')
    # ### end Alembic commands ###
