"""Migration - 3

Revision ID: 30eec26aacc8
Revises: b9f7493b871e
Create Date: 2021-02-25 21:12:30.236795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30eec26aacc8'
down_revision = 'b9f7493b871e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.create_unique_constraint(None, 'content', ['letter_id', 'paragraph_no', 'paragraph_text'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='unique')
    # ### end Alembic commands ###
