"""Chnage LetterTables

Revision ID: 53c88f88392c
Revises: 091e6df65ba7
Create Date: 2021-03-03 01:01:57.773956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53c88f88392c'
down_revision = '091e6df65ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lettertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('letter_id', sa.Integer(), nullable=False),
    sa.Column('table_no', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('letter_id', sa.INTEGER(), nullable=False),
    sa.Column('table_no', sa.INTEGER(), nullable=False),
    sa.Column('row', sa.INTEGER(), nullable=False),
    sa.Column('col', sa.INTEGER(), nullable=False),
    sa.Column('detail', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lettertable')
    # ### end Alembic commands ###
