"""Initial migration.

Revision ID: f3b55fe071b9
Revises: 
Create Date: 2021-02-25 20:55:18.325731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b55fe071b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   # op.add_column('content', sa.Column('option', sa.Integer(), nullable=True))
 #   op.alter_column('content', 'paragraph_no',
#               existing_type=sa.INTEGER(),
#               nullable=True)
#    op.alter_column('content', 'paragraph_text',
#               existing_type=sa.TEXT(),
#               nullable=False)
#    op.create_unique_constraint(None, 'content', ['letter_id', 'paragraph_no', 'paragraph_text'])
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='unique')
    op.alter_column('content', 'paragraph_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'paragraph_no',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('content', 'option')
    # ### end Alembic commands ###
